apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-key-vault-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: azure-key-vault-controller
  template:
    metadata:
      labels:
        name: azure-key-vault-controller
    spec:
      serviceAccountName: azure-key-vault-controller
      containers:
        - name: azure-key-vault-controller
          # Replace this with the built image name
          image: awareoss/azurekeyvaultcontroller:v0.0.1
          command:
          - azure-key-vault-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "azure-key-vault-controller"
